services:
  web:
    build:
      dockerfile: ./web/Dockerfile.dev
      context: .
      args:
        - NODE_ENV=${NODE_ENV:-development}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:5001}
        - VITE_PROXY_TARGET=${VITE_PROXY_TARGET:-localhost:5001}
    depends_on:
      core:
        condition: service_healthy
    volumes:
      - ./ui:/app/web
    ports:
      - "3000:3000"
    restart: always

  core:
    build:
      dockerfile: ./core/Dockerfile
      context: .
    ports:
      - "5001:5001"
    volumes:
      - ./core:/app
    environment:
      HF_TOKEN: ${HF_TOKEN:-}
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
