services:
  web:
    build:
      dockerfile: ./web/Dockerfile.dev
      context: .
      args:
        - NODE_ENV=${NODE_ENV:-development}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
    depends_on:
      core:
        condition: service_healthy
    volumes:
      - ./ui:/app/web
    ports:
      - "5173:5173"
    restart: always

  core:
    build:
      dockerfile: ./core/Dockerfile.dev
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    environment:
      HF_TOKEN: ${HF_TOKEN:-}
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
