services:
  web:
    image: rhobotsai/studio-web:latest
    depends_on:
      core:
        condition: service_healthy
    ports:
      - "5173:5173"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5173" ]
      interval: 30s
      timeout: 10s
      retries: 3

  core:
    image: rhobotsai/studio-core:latest
    ports:
      - "8000:8000"
    volumes:
      - core_data:/app/training_sessions
    environment:
      HF_TOKEN: ${HF_TOKEN:-}
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
volumes:
  core_data:
    driver: local
