FROM node:24-alpine

WORKDIR /app

# Add dependencies
RUN apk update && apk upgrade --no-cache libc6-compat libcrypto3 libssl3

RUN apk add --no-cache dumb-init curl

# Install dependencies
RUN corepack enable && corepack prepare pnpm@10.12.3 --activate

# Copy full source for development
COPY . .

RUN pnpm install --filter web --frozen-lockfile

# Pass build-time environment variables
ARG VITE_API_BASE_URL

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

EXPOSE 5173

WORKDIR /app/web

#CMD ["tail", "-f", "/dev/null"]
CMD ["pnpm", "run", "dev"]
